pub enum HttpError {
    BadRequest(String),
    Unauthorized(String),
    PaymentRequired(String),
    Forbidden(String),
    NotFound(String),
    MethodNotAllowed(String),
    NotAcceptable(String),
    ProxyAuthenticationRequired(String),
    RequestTimeout(String),
    Conflict(String),
    Gone(String),
    LengthRequired(String),
    PreconditionFailed(String),
    ContentTooLarge(String),
    UriTooLong(String),
    UnsupportedMediaType(String),
    RangeNotSatisfiable(String),
    ExpectationFailed(String),
    ImATeapot(String),
    MisdirectedRequest(String),
    UnprocessableContent(String),
    Locked(String),
    FailedDependency(String),
    TooEarly(String),
    UpgradeRequired(String),
    PreconditionRequired(String),
    TooManyRequests(String),
    RequestHeaderFieldsTooLarge(String),
    UnavailableForLegalReasons(String),
    InternalServerError(String),
    NotImplemented(String),
    BadGateway(String),
    ServiceUnavailable(String),
    GatewayTimeout(String),
    HttpVersionNotSupported(String),
    VariantAlsoNegotiates(String),
    InsuficientStorage(String),
    LoopDetected(String),
    NotExtended(String),
    NetworkAuthenticationRequired(String),
}

impl HttpError {
    pub fn error_code(&self) -> usize{
        match self {
            Self::BadRequest(_) => 400,
            Self::Unauthorized(_) => 401,
            Self::PaymentRequired(_) => 402,
            Self::Forbidden(_) => 403,
            Self::NotFound(_) => 404,
            Self::MethodNotAllowed(_) => 405,
            Self::NotAcceptable(_) => 406,
            Self::ProxyAuthenticationRequired(_) => 407,
            Self::RequestTimeout(_) => 408,
            Self::Conflict(_) => 409,
            Self::Gone(_) => 410,
            Self::LengthRequired(_) => 411,
            Self::PreconditionFailed(_) => 412,
            Self::ContentTooLarge(_) => 413,
            Self::UriTooLong(_) => 414,
            Self::UnsupportedMediaType(_) => 415,
            Self::RangeNotSatisfiable(_) => 416,
            Self::ExpectationFailed(_) => 417,
            Self::ImATeapot(_) => 418,
            Self::MisdirectedRequest(_) => 421,
            Self::UnprocessableContent(_) => 422,
            Self::Locked(_) => 423,
            Self::FailedDependency(_) => 424,
            Self::TooEarly(_) => 425,
            Self::UpgradeRequired(_) => 426,
            Self::PreconditionRequired(_) => 428,
            Self::TooManyRequests(_) => 429,
            Self::RequestHeaderFieldsTooLarge(_) => 431,
            Self::UnavailableForLegalReasons(_) => 451,
            Self::InternalServerError(_) => 500,
            Self::NotImplemented(_) => 501,
            Self::BadGateway(_) => 502,
            Self::ServiceUnavailable(_) => 503,
            Self::GatewayTimeout(_) => 504,
            Self::HttpVersionNotSupported(_) => 505,
            Self::VariantAlsoNegotiates(_) => 506,
            Self::InsuficientStorage(_) => 507,
            Self::LoopDetected(_) => 508,
            Self::NotExtended(_) => 510,
            Self::NetworkAuthenticationRequired(_) => 511,
        }
    }
    pub fn message(&self) -> String{
        match self {
            Self::BadRequest(msg) => msg.to_string(),
            Self::Unauthorized(msg) => msg.to_string(),
            Self::PaymentRequired(msg) => msg.to_string(),
            Self::Forbidden(msg) => msg.to_string(),
            Self::NotFound(msg) => msg.to_string(),
            Self::MethodNotAllowed(msg) => msg.to_string(),
            Self::NotAcceptable(msg) => msg.to_string(),
            Self::ProxyAuthenticationRequired(msg) => msg.to_string(),
            Self::RequestTimeout(msg) => msg.to_string(),
            Self::Conflict(msg) => msg.to_string(),
            Self::Gone(msg) => msg.to_string(),
            Self::LengthRequired(msg) => msg.to_string(),
            Self::PreconditionFailed(msg) => msg.to_string(),
            Self::ContentTooLarge(msg) => msg.to_string(),
            Self::UriTooLong(msg) => msg.to_string(),
            Self::UnsupportedMediaType(msg) => msg.to_string(),
            Self::RangeNotSatisfiable(msg) => msg.to_string(),
            Self::ExpectationFailed(msg) => msg.to_string(),
            Self::ImATeapot(msg) => msg.to_string(),
            Self::MisdirectedRequest(msg) => msg.to_string(),
            Self::UnprocessableContent(msg) => msg.to_string(),
            Self::Locked(msg) => msg.to_string(),
            Self::FailedDependency(msg) => msg.to_string(),
            Self::TooEarly(msg) => msg.to_string(),
            Self::UpgradeRequired(msg) => msg.to_string(),
            Self::PreconditionRequired(msg) => msg.to_string(),
            Self::TooManyRequests(msg) => msg.to_string(),
            Self::RequestHeaderFieldsTooLarge(msg) => msg.to_string(),
            Self::UnavailableForLegalReasons(msg) => msg.to_string(),
            Self::InternalServerError(msg) => msg.to_string(),
            Self::NotImplemented(msg) => msg.to_string(),
            Self::BadGateway(msg) => msg.to_string(),
            Self::ServiceUnavailable(msg) => msg.to_string(),
            Self::GatewayTimeout(msg) => msg.to_string(),
            Self::HttpVersionNotSupported(msg) => msg.to_string(),
            Self::VariantAlsoNegotiates(msg) => msg.to_string(),
            Self::InsuficientStorage(msg) => msg.to_string(),
            Self::LoopDetected(msg) => msg.to_string(),
            Self::NotExtended(msg) => msg.to_string(),
            Self::NetworkAuthenticationRequired(msg) => msg.to_string(),
        }
    }
}
